# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    {id: 10, size: 0.29625, name: marker_10},
    {id: 20, size: 0.09813, name: marker_20},
    {id: 30, size: 0.03183, name: marker_30},
    {id: 40, size: 0.29625, name: marker_40},
    {id: 50, size: 0.09813, name: marker_50},
    {id: 60, size: 0.03183, name: marker_60},
    {id: 70, size: 0.29625, name: marker_70},
    {id: 80, size: 0.09813, name: marker_80},
    {id: 90, size: 0.03183, name: marker_90}
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    # {
    #    name: 'marker_42',
    #    layout:
    #      [
    #        {id: 42, size: 0.16933},
    #        {id: 60, size: 0.05644}
    #      ]
    #  },
    #  {
    #    name: 'marker_25',
    #    layout:
    #      [
    #        {id: 48, size: 0.16933},
    #        {id: 25, size: 0.05644}
    #      ]
    #  }
  ]
